version: 0.1
prod:
  global:
    parameters:
      stack_name: serverless-url-redirect-distribution
      region: eu-north-1
      confirm_changeset: false
      capabilities: CAPABILITY_NAMED_IAM
      resolve_s3: true
  deploy:
    parameters:
      parameter_overrides:
        - Environment=prod
        - ApplicationName=serverless-redirect
        - DomainName=<YOUR DOMAIN NAME>
        - HostedZoneId=<YOUR HOSTED ZONE ID>
        - BaseSiteUrl=https://example.com
        - SSLCertificateArn=<SSL ARN FROM US-EAST-1>
