version: 0.1
prod:
  global:
    parameters:
      stack_name: serverless-auth-user-pool
      region: eu-north-1
      confirm_changeset: false
      capabilities: CAPABILITY_NAMED_IAM
      s3_prefix: serverless-auth-user-pool
      resolve_s3: true
  deploy:
    parameters:
      parameter_overrides:
        - Environment=
        - ApplicationName=
        - DomainName=
        - HostedAuthDomainPrefix=
        - UserPoolSecretName=
