version: 0.1
prod:
  global:
    parameters:
      stack_name: serverless-auth-lambda-edge
      region: us-east-1
      confirm_changeset: false
      capabilities: CAPABILITY_NAMED_IAM
      s3_prefix: serverless-auth-lambda-edge
      resolve_s3: true
  deploy:
    parameters:
      parameter_overrides:
        - Environment=
        - ApplicationName=
        - DomainName=
        - HostedZoneId=
        - SecretArn=
        - SecretName=
        - UserPoolId=
        - UserPoolHostedUiUrl=
        - UserPoolOauthEndpoint=
        - SsmParametersArn=
