AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Malware scanning of files uploaded to the service

Parameters:
  ApplicationName:
    Type: String
    Description: Name of owning application
    Default: image-moderation
  CommonInfraStackName:
    Type: String
    Description: Name of the common infra stack

Resources:
  S3MalwareProtectionPlan:
    Type: AWS::GuardDuty::MalwareProtectionPlan
    Properties:
      Actions:
        Tagging:
          Status: ENABLED
      ProtectedResource:
        S3Bucket:
          BucketName:
            Fn::ImportValue: !Sub ${CommonInfraStackName}:staging-bucket-name
      Role: !GetAtt S3MalwareProtectionPlanRole.Arn

  S3MalwareProtectionPlanRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - malware-protection-plan.guardduty.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: 'MalwareProtectionPlanPutS3EventRulePolicy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutRule
                  - events:DeleteRule
                  - events:PutTargets
                  - events:RemoveTargets
                Resource: "*"
                Condition:
                  StringLike:
                    events:ManagedBy: malware-protection-plan.guardduty.amazonaws.com
        - PolicyName: GuardDutyToMonitorEventBridgeManagedRule
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:DescribeRule
                  - events:ListTargetsByRule
                Resource: "*"
        - PolicyName: AllowPostScanTag
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObjectTagging
                  - s3:GetObjectTagging
                  - s3:PutObjectVersionTagging
                  - s3:GetObjectVersionTagging
                Resource: !Sub
                  - arn:aws:s3:::${BucketName}/*
                  - BucketName:
                      Fn::ImportValue: !Sub ${CommonInfraStackName}:staging-bucket-name
        - PolicyName: AllowEnableS3EventBridgeEvents
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource: !Sub
                  - arn:aws:s3:::${BucketName}
                  - BucketName:
                      Fn::ImportValue: !Sub ${CommonInfraStackName}:staging-bucket-name
        - PolicyName: AllowPutValidationObject
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub
                  - arn:aws:s3:::${BucketName}/malware-protection-resource-validation-object
                  - BucketName:
                      Fn::ImportValue: !Sub ${CommonInfraStackName}:staging-bucket-name
        - PolicyName: AllowCheckBucketOwnership
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !Sub
                  - arn:aws:s3:::${BucketName}
                  - BucketName:
                      Fn::ImportValue: !Sub ${CommonInfraStackName}:staging-bucket-name
        - PolicyName: AllowMalwareScan
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
              Resource: !Sub
                  - arn:aws:s3:::${BucketName}/*
                  - BucketName:
                      Fn::ImportValue: !Sub ${CommonInfraStackName}:staging-bucket-name
