AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Image Moderation Service Common Infrastructure
Parameters:
  ApplicationName:
    Type: String
    Description: Name of owning application
    Default: image-moderation

Resources:
  StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ApplicationName}-staging-bucket

  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ApplicationName}-storage-bucket

  QuarantineBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ApplicationName}-quarantine-bucket

  EventBridgeBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub ${ApplicationName}-event-bus


Outputs:
  StagingBucketName:
    Description: The name of the staging bucket
    Value: !Ref StagingBucket
    Export:
      Name: !Sub ${AWS::StackName}:staging-bucket-name

  StorageBucketName:
    Description: The name of the storage bucket
    Value: !Ref StorageBucket
    Export:
      Name: !Sub ${AWS::StackName}:storage-bucket-name

  QuarantineBucketName:
    Description: The name of the quarantine bucket
    Value: !Ref QuarantineBucket
    Export:
      Name: !Sub ${AWS::StackName}:quarantine-bucket-name

  EventBridgeBusName:
    Description: The EventBridge EventBus Name
    Value: !Ref EventBridgeBus
    Export:
      Name: !Sub ${AWS::StackName}:event-bus-name
      
  EventBridgeBusArn:
    Description: The EventBridge EventBus ARN
    Value: !GetAtt EventBridgeBus.Arn
    Export:
      Name: !Sub ${AWS::StackName}:event-bus-arn