version: 0.1
default:
  global:
    parameters:
      stack_name: serverless-statistics-lambda-edge
      region: us-east-1
      confirm_changeset: false
      capabilities: CAPABILITY_NAMED_IAM
      s3_prefix: serverless-statistics-lambda-edge
      resolve_s3: true
  deploy:
    parameters:
      parameter_overrides:
        - ApplicationName=
        - StateMachineArn=
