AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless statistics data analytics
Parameters:
  Application:
    Type: String
    Description: Name of owning application
  S3DataBucketName:
    Type: String
    Description: Name of S3 Bucket where data is stored

Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub ${Application}-database
        Description: !Sub Database for ${Application}

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub ${Application}-crawler
      Description: !Sub Crawler for ${Application}
      DatabaseName: !Ref GlueDatabase
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING
      Role: !GetAtt GlueCrawlerRole.Arn
      Schedule:
        ScheduleExpression: cron(0 1 * * ? * ) # Every night at 1 am
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Targets:
        S3Targets:
          - Path: !Sub s3://${S3DataBucketName}/

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3BucketAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${S3DataBucketName}/*
