version: 0.1
default:
  global:
    parameters:
      stack_name: serverless-statistics-cloudfront-dist
      region: eu-north-1
      confirm_changeset: false
      capabilities: CAPABILITY_NAMED_IAM
      s3_prefix: serverless-statistics-cloudfront-dist
      resolve_s3: true
  deploy:
    parameters:
      parameter_overrides:
        - ApplicationName=
        - BucketNameSuffix=statistics
        - DataIngestlambdaArn=
