AWSTemplateFormatVersion: 2010-09-09
Description: Setup and configure the Service ECR repository

Parameters:
  Application:
    Type: String
    Description: Name of the application owning all resources
  Service:
    Type: String
    Description: Name of the service

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${Application}-${Service}
      ImageScanningConfiguration:
        ScanOnPush: True
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

Outputs:
  ECRRepositoryName:
    Value: !Ref EcrRepository
    Export:
      Name: !Sub ${AWS::StackName}:ecr-repository
