version: 0.1
default:
  global:
    parameters:
      stack_name: slack-http-api-demo
      region: eu-north-1
      confirm_changeset: false
      capabilities: CAPABILITY_NAMED_IAM
      s3_prefix: slack-http-api-demo
      resolve_s3: true
  deploy:
    parameters:
      parameter_overrides:
        - Application=slack-http-api-demo
